# Generated by Django 4.2 on 2023-05-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("created", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=1000)),
                ("date_added", models.DateField(auto_now=True)),
                ("payload", models.FileField(upload_to="books/")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="book-cover/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_category",
                        to="bms.category",
                    ),
                ),
            ],
        ),
    ]
