# Generated by Django 4.2 on 2023-05-14 11:13

import django.contrib.postgres.search
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bms", "0002_alter_book_id_alter_book_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="idx",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b145306f-98b9-40a8-8cc7-686e7a1d2719"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
