# Generated by Django 4.2 on 2023-05-14 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bms", "0003_book_idx_book_search_vector_category_search_vector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("38ef4b73-4676-4e97-ad34-a9624db81c30"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
