# Generated by Django 4.2 on 2023-05-14 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bms", "0004_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("47a619c9-cf3c-4ddb-b782-da7fe5f17ae4"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
