# Generated by Django 4.2 on 2023-05-14 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bms", "0005_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7b2e5023-5973-45d3-8358-f6446f840b35"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
