# Generated by Django 4.2 on 2023-05-14 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bms", "0006_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6cc70909-dd2f-4227-ae3b-747e01dc8640"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
