# Generated by Django 4.2.6 on 2023-12-06 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0007_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='idx',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('86246467-28b0-4809-b81d-72c5d6fede55'), primary_key=True, serialize=False),
        ),
    ]
