# Generated by Django 4.2.6 on 2023-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0009_alter_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
